### ISSUE TITLE
Have you passed an image w/an object together over the same channel?

### ISSUE THREAD

**Issue by ljunquera** [shoaibsaikat/Android-Channel-Client-File-Transfer#1]
This is a great example. Thank you. I'm not sure I have seen another ChannelClient example. Have you ever passed an object with an image in the same channel/transaction? Also do you have an example of ChannelClient with a WearableListenerService on the wearable?

**Comment by shoaibsaikat** [comment]
Thank you for checking my repo. No I have not done those yet. If I do I'll let you know.
